<a href="https://colab.research.google.com/github/Manmith1321/AIML/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
input=[1,2,3]
weights=[0,0,0.1]
bais=1
output=input[0]*weights[0]+input[1]*weights[1]+input[2]*weights[2]+bais
print(output)

1.3


In [2]:
input=[0,0.4,0.8,0.3,1]
weight1=[0.3,0.2,0.1,0.4]
weight2=[0.4,0.1,0.1,0.2]
weight3=[0.2,0.2,0.1,0.8]
bais1=0.5
bais2=0.3
bais3=0.6
output = [input[0]*weight1[0]+input[1]*weight1[1]+input[2]*weight1[2]+input[3]*weight1[3]+bais1,
         input[0]*weight1[0]+input[1]*weight1[1]+input[2]*weight1[2]+input[3]*weight1[3]+bais2,
         input[0]*weight1[0]+input[1]*weight1[1]+input[2]*weight1[2]+input[3]*weight1[3]+bais3]
print(output)

[0.78, 0.5800000000000001, 0.88]


In [3]:
import numpy as np
input=np.array([1,2,3,2.5])
weight=np.array([[0.3,0.2,0.1,0.4],[0.4,0.1,0.1,0.2],[0.2,0.2,0.1,0.8]])
bais=np.array([1,2,3])
output=np.dot(weight,input)+bais
print(output)

[3.  3.4 5.9]


In [4]:
import numpy as np
def relu(x):
  return np.maximum(0,x)
  input=np.array([1,2,3,2.5])
  weight=np.array([[0.3,0.2,0.1,0.4],[0.4,0.1,0.1,0.2],[0.2,0.2,0.1,0.8]])
  bais=np.array([1,2,3])
output=np.dot(weight,input)+bais
output=relu(output)
print(output)

[3.  3.4 5.9]


In [5]:
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return np.maximum(0,x)

inputs = np.array([0.4, 0.3, 1, 0.8])
weights = np.array([
    [0.3, 0.2, 0.1, 0.4],
    [0.4, 0.1, -0.1, 0.2],
    [0.2, -0.2, -0.1, 0.8]
])
biases = np.array([0.5, 0.3, 0.6])

output = relu(np.dot(weights, inputs) + biases)
#Activation ReLU activation function
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)

[1.1  0.55 1.16]
[0.75026011 0.63413559 0.76133271]
